 # -*- coding: utf-8 -*-

"""
Django settings for GlobalSettings project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, sys

from common import Define

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '23l7eje2!27vim5v&ou60py6k@=3yc78_uwie=i+#ry-lmr7ex'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
#CSRF_COOKIE_HTTPONLY = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

	# 第三方库
    'sortedm2m',

    'file_manage.apps.MyadminConfig',
    'crond.apps.CrondConfig',
    # 入口
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'common.middleware.TracbackMiddleware',  # 在Debug=False时，输出脚本错误日志
]

ROOT_URLCONF = 'GlobalSettings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 模版文件的存放路径，可以有多个
        'DIRS': [
            BASE_DIR + "/templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GlobalSettings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default' : {
        #'ENGINE'   : 'django.db.backends.mysql',
        'ENGINE'   : 'mysql.connector.django',
        'NAME'     : 'file_manage',
        'USER'     : 'root',
        'PASSWORD' : '123456',
        'HOST'     : 'localhost',
        'PORT'     : '3306',
        'OPTIONS'  : {
            'autocommit': True,
        }
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#USE_TZ = True
USE_TZ = False

DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# 初始化数据文件夹
FIXTURE_DIRS = (os.path.join(BASE_DIR,'initdata',),)

# 静态文件的存放路径，可以有多个
STATICFILES_DIRS  = (
    os.path.join(BASE_DIR, "static"),
)

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
if sys.platform == "win32":
	MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
	MEDIA_ROOT = "/var/www/html.cwtv.media/"

# If you want to use {{ MEDIA_URL }} in your templates,
# add 'django.template.context_processors.media' in the 'context_processors' option of TEMPLATES.
# Example: "http://media.example.com/"
MEDIA_URL = "/media/"


# The maximum size (in bytes) that an upload will be before it gets streamed to the file system.
# See Managing files for details.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5M * 1024 * 1024

# The directory to store data to (typically files larger than FILE_UPLOAD_MAX_MEMORY_SIZE) temporarily while uploading files.
# If None, Django will use the standard temporary directory for the operating system. For example,
# this will default to /tmp on *nix-style operating systems.
FILE_UPLOAD_TEMP_DIR = None

if sys.platform == "win32":
    toLocalFile = {
            'level' : 'DEBUG',
            'class' : 'logging.FileHandler',
            'filename' : os.path.join(BASE_DIR, 'logs/log.txt'),
            'encoding' : 'utf-8',
            'formatter' : 'verbose',
    }
else:
    toLocalFile = {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.TimedRotatingFileHandler',
            'filename' : os.path.join(BASE_DIR, 'logs/log.txt'),
            'when' : 'D',
            'interval' : 1,
            'encoding' : 'utf-8',
            'formatter' : 'verbose',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'toLocalFile' : toLocalFile,
    },
    'loggers': {
        'default': {
            #'handlers': ['console'],
            'handlers': ['toLocalFile'],
            'level': 'DEBUG',
            'propagate' : True,
        },
    }
}

# logging config for django custom command
COMMAND_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'toCommandLogFile' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.TimedRotatingFileHandler',
            'filename' : os.path.join(BASE_DIR, 'logs/command.log'),
            'when' : 'D',
            'interval' : 1,
            'encoding' : 'utf-8',
            'formatter' : 'verbose',
        },
    },
    'loggers': {
        'command': {
            'handlers': ['toCommandLogFile'],
            'level': 'DEBUG',
            'propagate' : True,
        },
    }
}



# 用于生成签名的key
UBOX_SECRET = "T9daEpHABVKeTxHxF3bzBKUW11vGd0lP"

# uid的默认前缀
UID_PREFIX = "UBOX"

AREA_ID = 0
POH_TYPE = 0




# 访问者时间（单位：秒）
# 访问者切换页面的时间不超过这个时间，就认为前后两个页面的访问是同一阶段的访问
PAGEVIEW_VISITOR_TIME = 60 * 30



LOGIN_URL = 'login'